# 这是一个参数文件
# 去你妹的yaml! 我再也不用yaml了！简简单单多好！

# part 4 里定义的参数

detector=SIFT
descriptor=SIFT
good_match_threshold=50

# camera
camera.cx=320.1;
camera.cy=247.6;
camera.fx=535.4;
camera.fy=539.2;
camera.scale=1000.0;


# part 5 
# 数据相关
# 起始与终止索引
start_index=1
end_index=700
# 数据所在目录
rgb_dir=/media/fb/software/dataset/TUM/HandheldSLAM/rgbd_dataset_freiburg1_360/rgb/
rgb_extension=.png
depth_dir=/media/fb/software/dataset/TUM/HandheldSLAM/rgbd_dataset_freiburg1_360/depth/
depth_extension=.png

path_to_association=/media/fb/software/dataset/TUM/HandheldSLAM/rgbd_dataset_freiburg2_desk/fr2_desk.txt
path_to_sequence=/media/fb/software/dataset/TUM/HandheldSLAM/rgbd_dataset_freiburg2_desk
# 点云分辨率
voxel_grid=0.1
# 是否实时可视化
visualize_pointcloud=yes
# 最小匹配数量
min_good_match=10
# 最小内点
min_inliers=5
# 最大运动误差
max_norm=0.3



#part 7
keyframe_threshold=0.1
max_norm_lp=5.0
# Loop closure
check_loop_closure=yes
nearby_loops=5
random_loops=5